name: device_info_ios
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/DrillCorp

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_platform_interface:
    path: ../../flutter_projects/device_info_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DeviceInfoIosPlugin
